theme: jekyll-theme-minimal
title: Gabriel Tinsley homepage
description: Here are some of my favorite projects so far
- Final Project for my Intro to Full Stack Web Development CS208 [Local Host CS208 Website](https://github.com/BSU-CS-208-summer-2024-classroom/5-1-final-project-final-project-7)
- Fianl Project for my Computer Science I CS121 [TicTacToe game](https://github.com/Boise-State-University-CS-121/cs121-2024-sp-project3-gabrieltinsley/tree/main/Project3)
